import DesignProvider from "../common/providers/design_provider";
import "./globals.css";
import Header from "./Header";
import Footer from "./Footer";
import "../../global.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <DesignProvider>{children}</DesignProvider>
        <Footer />
      </body>
    </html>
  );
}
